### PR TITLE
NAT Punch 2.0

### PR DESCRIPTION
**Pull request by trippyone**
This solution uses LiteNetLib instead of the STUN library to perform NAT punching. It requires an external server (FikaNatPunchServer) running alongside AKI to relay the punching requests between server and clients, which can be found here: https://github.com/project-fika/Fika-ServerTools. The server must be externally reachable on port 6790 by default (configurable).

Pros:
* Does not require additional libraries such as STUN (reduced dependencies). Uses the same network library as Fika for game play networking.
* Does not rely on Google STUN services (which can be potentially problematic for a number of reasons) for NAT punching.
* Cleaner code and improved NAT punching reliability.
* No changes required on Fika-Server.

Cons:
* Requires an externally reachable server (vps/dedi) running FikaNatPunchServer with AKI server.
* FikaNatPunchServer is running independently from AKI server, so it cannot be managed by it at this current stage.

One could make the argument that we should use AKI server as the NAT punching handler. However, there are a few caveats to this:
* We need to provide a UDP connection from AKI server (to allow for NAT punching and packet destination redirection).
* The UDP connection must be compatible with LiteNetLib which does not have a NodeJS module implementation.
* We could use a simple UDP client in .NET instead that works with NodeJS. However, we would have to do some funky local port re-binding between the UDP client and LiteNetLib to be able to hijack the route that was opened using NAT punching. This technique can be seen with the current NAT punching implementation and I really dislike it. The NAT punched route only stays open for a limited amount of time in routers and you have to maintain the route open before a client actually connects to the Fika server. This new implementation makes this process MUCH easier.

If you have any concerns do not hesitate to comment on this PR.

Edit: I am potentially looking at controlling the NatPunchServer process from Fika-Server. This way we would only need to start AKI server and we would only have one config file which we can then transmit to the clients.

### CODE REVIEW

**Comment by Lacyway** [comment]
As discussed in DMs, my only concern is making the port client-sided. In my opinion, it should be set and retrieved from the server as the host will always know which port they set, removing potential user errors.

Apart from that, running an external application should not be an issue (apart from Linux users, maybe? SPT is not "officially" supporting it anyway afaik, but I'm sure the application can be used there if setup correctly).

We could potentially make the SPT server handle the application through our server mod and launch it with parameters (e.g. the port).

Very nice PR 👍

**Comment by trippyone** [comment]
> As discussed in DMs, my only concern is making the port client-sided. In my opinion, it should be set and retrieved from the server as the host will always know which port they set, removing potential user errors.
> 
> Apart from that, running an external application should not be an issue (apart from Linux users, maybe? SPT is not "officially" supporting it anyway afaik, but I'm sure the application can be used there if setup correctly).
> 
> We could potentially make the SPT server handle the application through our server mod and launch it with parameters (e.g. the port).
> 
> Very nice PR 👍

I will look into making some changes in Fika-Server to handle the FikaNatPunch server from AKI. It should allows us to do what you're suggesting.

**Comment by maxomatic458** [comment]
@trippyone The FikaNatPunch server would require port forwarding correct? (so proxies or vpns would not work as the connections would appear as being local)

**Comment by trippyone** [comment]
> @trippyone The FikaNatPunch server would require port forwarding correct? (so proxies or vpns would not work as the connections would appear as being local)

Yes, you cannot perform NAT punching if you're on the same network.

**Comment by trippyone** [comment]
I consider this PR completed and ready for review.

**Comment by Lacyway** [comment]
Will merge when server PR is merged.

**Pull request merged**
