### PR TITLE
Additional advanced options for ping & name plates

### PR DESCRIPTION
**Pull request by Outshynd**
I had wanted to add an option for Fontaine's FOV Fixes mod users to be able to still display name plates and pings when aiming with an optic scope, but to not apply the optic's zoom&FOV to the location of the name plate / ping sprite. To that end, I added a boolean toggle for each as an 'Advanced' option, not normally visible.

Also added parts of a feature request from ArcticFox037 on Discord as advanced options: minimum ping opacity and a toggle to not scale ping based on distance.

No breaking changes, defaults are set up so that anyone who does not look in the Advanced settings of Configuration Manager will not even notice a difference.

### CODE REVIEW

**Comment by Outshynd** [comment]
I just now realized I was working on an old version of the codebase. Dumb.

**Comment by Lacyway** [comment]
Do you have a 3.9.0 build you can use to do this and retarget?
I've kind of halted development on 3.8.3 unless critical bugfixes are needed.

3.9.0 seems like it's not far off and it has big improvements so I decided to focus development on it instead.

**Comment by Outshynd** [comment]
I don't have a 3.9.0 build, no, sorry. These are pretty surface level changes, I'm sure they can integrate straight in to 3.9.0, I just haven't set that up, nor do I have plans to until my group switches to 3.9.0 as stable. No big deal, I can re-implement later or whatever works.

**Comment by Lacyway** [comment]
No worries, leave the PR and I'll migrate it to 3.9.0 next time I work on it.

**Comment by Lacyway** [comment]
Will try to merge this today.

**Review by Lacyway — APPROVED** [review]

**Pull request merged**
