### PR TITLE
Fix constructor exception in CoopObservedFirearmController

### PR DESCRIPTION
**Pull request by ArchangelWTF**
Relatively simple and straightforward fix, Unity doesn't want Time.time to be run immediately upon construction of a class throwing an exception and causing further exceptions down the line whenever checking ammo or any other actions occur.

### CODE REVIEW

**Review by Lacyway — APPROVED** [review]
Nice one, thanks.
I haven't noticed any exceptions here, how were they caused exactly?

**Comment by ArchangelWTF** [comment]
@Lacyway It seems to happen immediately upon spawning into a raid even on master (Which is why I initially targeted that) and can only be observed on the client, afterwards this seems to cause other exceptions that has to do anything hands controller related it didn't initialize properly.

image

**Comment by Lacyway** [comment]
> @Lacyway It seems to happen immediately upon spawning into a raid even on master (Which is why I initially targeted that) and can only be observed on the client, afterwards this seems to cause other exceptions that has to do anything hands controller related it didn't initialize properly.
> 
> image
> 

Is this happening every raid for you? I have never seen this exception before. Very interesting find. Could it be a mod?

**Comment by ArchangelWTF** [comment]
Nothing mod related as just for a sanity check I moved those out, when I got the exception that I screenshotted I was only running the latest FIKA (master) and the latest AKI 3.8.3 libraries.

**Comment by Lacyway** [comment]
Damn, that's weird. The change does no harm anyway and prevents future errors. Thanks again!

**Pull request merged**
